AAA = ...
    -((gs*r - 1)^2*(cos(DU*N) - 1)) ...
    / ...
    (...
    + N^2 ...
    - N^2*cos(DU) ...
    + gs^2*r^2 ...
    - gs^2*r^2*cos(DU*N) ...
    - N*gs*r ...
    + N*gs*r*cos(DU) ...
    - N*gs*r*cos(DU - DU*N) ...
    + N*gs*r*cos(DU*N)...
    )

BBB = ...
    -((gs*r - 1)^2*(cos(DU*N) - 1)) ...
    / ...
    ( ...
    + N^2 ...
    - N^2*cos(DU) ...
    + gs^2*r^2 ...
    - gs^2*r^2*cos(DU*N) ...
    - N*gs*r ...
    + N*gs*r*cos(DU) ...
    - N*gs*r*cos(DU - DU*N) ...
    + N*gs*r*cos(DU*N) ...
    )

